name = "the-tap-pincher"
main = "workers/pincher-worker/src/index.ts"
compatibility_date = "2026-08-01"
compatibility_flags = ["nodejs_compat"]

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTORIZE_INDEX"
index_name = "tap-memory"

[[kv_namespaces]]
binding = "TAP_CONFIG"
id = "9df13fe0b353496eb9dee10366e3affc"
